[2023-12-24T14:03:43.911+0000] {processor.py:161} INFO - Started process (PID=84) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:03:43.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:03:43.917+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:03:43.917+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:03:45.367+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:03:45.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:03:45.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:03:45.390+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 1.484 seconds
[2023-12-24T14:05:43.084+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:05:43.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:05:43.099+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:05:43.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:05:46.789+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:05:46.782+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:05:46.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:05:46.846+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 3.771 seconds
[2023-12-24T14:06:33.459+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:06:33.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:06:33.471+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:06:33.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:06:34.217+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:06:34.210+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:06:34.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:06:34.254+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.804 seconds
[2023-12-24T14:07:04.310+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:07:04.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:07:04.317+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:04.316+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:07:04.926+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:04.924+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:07:04.927+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:07:04.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.653 seconds
[2023-12-24T14:07:35.741+0000] {processor.py:161} INFO - Started process (PID=155) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:07:35.766+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:07:35.799+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:35.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:07:37.030+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:07:37.025+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:07:37.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:07:37.092+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 1.362 seconds
[2023-12-24T14:08:07.176+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:08:07.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:08:07.184+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:07.184+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:08:08.127+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:08.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:08:08.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:08:08.165+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.996 seconds
[2023-12-24T14:08:38.485+0000] {processor.py:161} INFO - Started process (PID=274) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:08:38.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:08:38.493+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:38.492+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:08:39.172+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:08:39.170+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:08:39.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:08:39.204+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.725 seconds
[2023-12-24T14:09:09.324+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:09:09.327+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:09:09.332+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:09.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:09:10.215+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:10.213+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:09:10.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:09:10.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.925 seconds
[2023-12-24T14:09:40.613+0000] {processor.py:161} INFO - Started process (PID=394) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:09:40.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:09:40.619+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:40.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:09:41.239+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:09:41.237+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:09:41.240+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:09:41.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.662 seconds
[2023-12-24T14:10:12.066+0000] {processor.py:161} INFO - Started process (PID=455) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:10:12.070+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:10:12.083+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:12.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:10:12.831+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:12.829+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:10:12.832+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:10:12.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.803 seconds
[2023-12-24T14:10:42.942+0000] {processor.py:161} INFO - Started process (PID=513) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:10:42.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:10:42.948+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:42.947+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:10:43.427+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:10:43.425+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:10:43.428+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:10:43.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.511 seconds
[2023-12-24T14:11:14.194+0000] {processor.py:161} INFO - Started process (PID=572) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:11:14.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:11:14.202+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:14.201+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:11:14.969+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:14.967+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:11:14.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:11:15.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.823 seconds
[2023-12-24T14:11:45.147+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:11:45.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:11:45.168+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:45.167+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:11:46.196+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:11:46.193+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:11:46.198+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:11:46.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 1.128 seconds
[2023-12-24T14:12:16.545+0000] {processor.py:161} INFO - Started process (PID=697) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:12:16.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:12:16.553+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:16.553+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:12:17.434+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:17.431+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:12:17.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:12:17.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.942 seconds
[2023-12-24T14:12:47.605+0000] {processor.py:161} INFO - Started process (PID=756) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:12:47.606+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:12:47.611+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:47.610+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:12:48.391+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:12:48.388+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:12:48.392+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:12:48.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.825 seconds
[2023-12-24T14:13:18.545+0000] {processor.py:161} INFO - Started process (PID=817) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:13:18.548+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:13:18.556+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:18.555+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:13:19.603+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:19.600+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:13:19.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:13:19.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 1.173 seconds
[2023-12-24T14:13:50.505+0000] {processor.py:161} INFO - Started process (PID=878) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:13:50.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:13:50.511+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:50.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:13:51.230+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:13:51.228+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:13:51.231+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:13:51.257+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.756 seconds
[2023-12-24T14:14:22.149+0000] {processor.py:161} INFO - Started process (PID=941) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:14:22.154+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:14:22.163+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:22.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:14:22.986+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:22.983+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:14:22.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:14:23.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.885 seconds
[2023-12-24T14:14:53.279+0000] {processor.py:161} INFO - Started process (PID=1002) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:14:53.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:14:53.285+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:53.284+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:14:53.938+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:14:53.935+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:14:53.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:14:53.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.694 seconds
[2023-12-24T14:15:24.176+0000] {processor.py:161} INFO - Started process (PID=1064) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:15:24.178+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:15:24.184+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:24.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:15:24.840+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:24.837+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:15:24.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:15:24.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.704 seconds
[2023-12-24T14:15:54.957+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:15:54.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:15:54.965+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:54.964+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:15:55.567+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:15:55.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:15:55.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:15:55.593+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.644 seconds
[2023-12-24T14:16:25.794+0000] {processor.py:161} INFO - Started process (PID=1184) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:16:25.797+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:16:25.805+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:16:25.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:16:26.597+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:16:26.594+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:16:26.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:16:26.629+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.843 seconds
[2023-12-24T14:18:35.442+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:18:35.462+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:18:35.469+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:18:35.468+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:18:38.673+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:18:38.665+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:18:38.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:18:38.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 3.288 seconds
[2023-12-24T14:19:08.814+0000] {processor.py:161} INFO - Started process (PID=106) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:19:08.816+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:19:08.829+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:08.828+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:19:10.130+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:10.122+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:19:10.131+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:19:10.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 1.416 seconds
[2023-12-24T14:19:40.509+0000] {processor.py:161} INFO - Started process (PID=166) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:19:40.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:19:40.516+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:40.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:19:41.183+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:19:41.181+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:19:41.184+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:19:41.233+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.730 seconds
[2023-12-24T14:20:11.313+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:20:11.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:20:11.321+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:11.320+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:20:12.041+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:12.038+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 12, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:20:12.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:20:12.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.801 seconds
[2023-12-24T14:20:16.015+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:20:16.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:20:16.030+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:16.027+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:20:16.064+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:16.060+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:20:16.066+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:20:16.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.171 seconds
[2023-12-24T14:20:46.897+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:20:46.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:20:46.906+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:46.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:20:46.920+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:20:46.917+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:20:46.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:20:46.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.078 seconds
[2023-12-24T14:21:17.685+0000] {processor.py:161} INFO - Started process (PID=361) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:21:17.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:21:17.692+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:17.691+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:21:17.703+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:17.701+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:21:17.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:21:17.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.064 seconds
[2023-12-24T14:21:34.969+0000] {processor.py:161} INFO - Started process (PID=395) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:21:34.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:21:34.976+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:34.975+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:21:34.987+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:21:34.985+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:21:34.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:21:35.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.054 seconds
[2023-12-24T14:22:05.500+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:22:05.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:22:05.507+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:05.507+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:22:05.515+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:05.513+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:22:05.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:22:05.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.049 seconds
[2023-12-24T14:22:35.918+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:22:35.920+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:22:35.927+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:35.927+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:22:35.939+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:22:35.938+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:22:35.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:22:36.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.147 seconds
[2023-12-24T14:23:06.169+0000] {processor.py:161} INFO - Started process (PID=569) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:23:06.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:23:06.177+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:06.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:23:06.188+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:06.185+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:23:06.189+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:23:06.229+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.069 seconds
[2023-12-24T14:23:36.305+0000] {processor.py:161} INFO - Started process (PID=627) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:23:36.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:23:36.313+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:36.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:23:36.323+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:23:36.321+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:23:36.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:23:36.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.064 seconds
[2023-12-24T14:24:06.478+0000] {processor.py:161} INFO - Started process (PID=685) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:24:06.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:24:06.486+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:06.485+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:24:06.496+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:06.494+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from postgres.data_tools import SqlUtils
ModuleNotFoundError: No module named 'postgres'
[2023-12-24T14:24:06.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:24:06.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.062 seconds
[2023-12-24T14:24:11.602+0000] {processor.py:161} INFO - Started process (PID=687) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:24:11.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:24:11.610+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:11.609+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:24:11.624+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:11.622+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:24:11.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:24:11.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.068 seconds
[2023-12-24T14:24:41.929+0000] {processor.py:161} INFO - Started process (PID=745) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:24:41.931+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:24:41.936+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:41.935+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:24:41.951+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:24:41.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:24:41.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:24:42.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.092 seconds
[2023-12-24T14:25:12.185+0000] {processor.py:161} INFO - Started process (PID=803) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:25:12.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:25:12.192+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:12.191+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:25:12.203+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:12.201+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:25:12.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:25:12.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.059 seconds
[2023-12-24T14:25:42.428+0000] {processor.py:161} INFO - Started process (PID=861) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:25:42.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:25:42.433+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:42.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:25:42.446+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:25:42.442+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:25:42.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:25:42.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.082 seconds
[2023-12-24T14:26:12.698+0000] {processor.py:161} INFO - Started process (PID=919) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:26:12.700+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:26:12.705+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:12.705+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:26:12.713+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:12.711+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:26:12.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:26:12.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.056 seconds
[2023-12-24T14:26:42.901+0000] {processor.py:161} INFO - Started process (PID=977) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:26:42.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:26:42.909+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:42.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:26:42.919+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:26:42.917+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:26:42.920+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:26:42.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.065 seconds
[2023-12-24T14:27:13.752+0000] {processor.py:161} INFO - Started process (PID=1035) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:27:13.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:27:13.759+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:13.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:27:13.771+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:13.768+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:27:13.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:27:13.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.067 seconds
[2023-12-24T14:27:44.249+0000] {processor.py:161} INFO - Started process (PID=1093) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:27:44.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:27:44.256+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:44.255+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:27:44.266+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:27:44.264+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:27:44.268+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:27:44.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.068 seconds
[2023-12-24T14:28:14.401+0000] {processor.py:161} INFO - Started process (PID=1151) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:28:14.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:28:14.407+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:14.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:28:14.415+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:14.413+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:28:14.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:28:14.445+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.047 seconds
[2023-12-24T14:28:44.662+0000] {processor.py:161} INFO - Started process (PID=1209) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:28:44.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:28:44.676+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:44.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:28:44.687+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:28:44.685+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:28:44.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:28:44.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.063 seconds
[2023-12-24T14:29:14.788+0000] {processor.py:161} INFO - Started process (PID=1267) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:29:14.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:29:14.795+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:14.795+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:29:14.807+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:14.804+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:29:14.808+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:29:14.848+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.066 seconds
[2023-12-24T14:29:45.464+0000] {processor.py:161} INFO - Started process (PID=1324) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:29:45.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:29:45.470+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:45.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:29:45.478+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:29:45.476+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:29:45.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:29:45.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.053 seconds
[2023-12-24T14:30:16.033+0000] {processor.py:161} INFO - Started process (PID=1380) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:30:16.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:30:16.039+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:16.039+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:30:16.050+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:16.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:30:16.051+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:30:16.086+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.059 seconds
[2023-12-24T14:30:46.739+0000] {processor.py:161} INFO - Started process (PID=1438) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:30:46.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:30:46.750+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:46.750+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:30:46.782+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:30:46.777+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:30:46.784+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:30:46.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.124 seconds
[2023-12-24T14:31:17.353+0000] {processor.py:161} INFO - Started process (PID=1496) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:31:17.355+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:31:17.359+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:31:17.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:31:17.368+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:31:17.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:31:17.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:31:17.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.058 seconds
[2023-12-24T14:33:18.837+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:33:18.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:33:18.864+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:18.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:33:18.909+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:18.890+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:33:18.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:33:18.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.166 seconds
[2023-12-24T14:33:49.260+0000] {processor.py:161} INFO - Started process (PID=98) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:33:49.261+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:33:49.266+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:49.266+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:33:49.277+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:33:49.274+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:33:49.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:33:49.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.072 seconds
[2023-12-24T14:34:19.383+0000] {processor.py:161} INFO - Started process (PID=156) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:34:19.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:34:19.391+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:19.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:34:19.402+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:19.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:34:19.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:34:19.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.069 seconds
[2023-12-24T14:34:49.816+0000] {processor.py:161} INFO - Started process (PID=214) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:34:49.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:34:49.823+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:49.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:34:49.833+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:34:49.830+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:34:49.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:34:49.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.060 seconds
[2023-12-24T14:35:20.167+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:35:20.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:35:20.179+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:20.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:35:20.203+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:20.200+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 13, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:35:20.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:35:20.242+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.084 seconds
[2023-12-24T14:35:49.331+0000] {processor.py:161} INFO - Started process (PID=330) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:35:49.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:35:49.338+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:49.337+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:35:50.018+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:35:50.016+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:35:50.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:35:50.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.726 seconds
[2023-12-24T14:36:20.608+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:36:20.614+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:36:20.621+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:20.620+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:36:21.410+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:21.408+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:36:21.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:36:21.439+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.839 seconds
[2023-12-24T14:36:51.818+0000] {processor.py:161} INFO - Started process (PID=447) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:36:51.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:36:51.824+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:51.823+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:36:52.290+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:36:52.288+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:36:52.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:36:52.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.503 seconds
[2023-12-24T14:37:23.099+0000] {processor.py:161} INFO - Started process (PID=507) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:37:23.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:37:23.106+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:23.106+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:37:23.717+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:23.715+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:37:23.718+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:37:23.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.651 seconds
[2023-12-24T14:37:53.878+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:37:53.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:37:53.885+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:53.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:37:54.879+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:37:54.877+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:37:54.881+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:37:54.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 1.057 seconds
[2023-12-24T14:38:25.622+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:38:25.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:38:25.630+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:25.629+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:38:26.479+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:26.477+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:38:26.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:38:26.508+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.894 seconds
[2023-12-24T14:38:57.063+0000] {processor.py:161} INFO - Started process (PID=685) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:38:57.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:38:57.071+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:57.070+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:38:57.912+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:38:57.906+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:38:57.921+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:38:58.009+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.954 seconds
[2023-12-24T14:39:28.210+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:39:28.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:39:28.217+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:39:28.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:39:28.944+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:39:28.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:39:28.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:39:28.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.771 seconds
[2023-12-24T14:39:59.240+0000] {processor.py:161} INFO - Started process (PID=806) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:39:59.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:39:59.248+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:39:59.247+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:40:00.178+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:40:00.175+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:40:00.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:40:00.211+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.978 seconds
[2023-12-24T14:40:30.422+0000] {processor.py:161} INFO - Started process (PID=869) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:40:30.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:40:30.431+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:40:30.430+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:40:31.117+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:40:31.114+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:40:31.118+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:40:31.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.770 seconds
[2023-12-24T14:41:01.623+0000] {processor.py:161} INFO - Started process (PID=928) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:41:01.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:41:01.632+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:01.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:41:02.373+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:02.370+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:41:02.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:41:02.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.784 seconds
[2023-12-24T14:41:32.705+0000] {processor.py:161} INFO - Started process (PID=990) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:41:32.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:41:32.712+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:32.711+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:41:33.404+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:41:33.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:41:33.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:41:33.441+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.745 seconds
[2023-12-24T14:42:03.941+0000] {processor.py:161} INFO - Started process (PID=1049) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:42:03.943+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:42:03.948+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:03.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:42:04.664+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:04.661+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:42:04.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:42:04.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.760 seconds
[2023-12-24T14:42:35.134+0000] {processor.py:161} INFO - Started process (PID=1111) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:42:35.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:42:35.142+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:35.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:42:36.046+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:42:36.043+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:42:36.047+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:42:36.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.968 seconds
[2023-12-24T14:43:07.053+0000] {processor.py:161} INFO - Started process (PID=1173) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:43:07.055+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:43:07.060+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:07.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:43:07.791+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:07.789+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:43:07.791+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:43:07.818+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.771 seconds
[2023-12-24T14:43:38.091+0000] {processor.py:161} INFO - Started process (PID=1232) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:43:38.093+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:43:38.098+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:38.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:43:38.838+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:43:38.837+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:43:38.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:43:38.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.796 seconds
[2023-12-24T14:44:09.239+0000] {processor.py:161} INFO - Started process (PID=1291) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:44:09.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:44:09.245+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:09.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:44:09.915+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:09.913+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:44:09.917+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:44:09.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.714 seconds
[2023-12-24T14:44:40.109+0000] {processor.py:161} INFO - Started process (PID=1353) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:44:40.112+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:44:40.119+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:40.119+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:44:40.832+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:44:40.830+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:44:40.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:44:40.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.763 seconds
[2023-12-24T14:45:11.012+0000] {processor.py:161} INFO - Started process (PID=1414) to work on /opt/airflow/dags/load_data.py
[2023-12-24T14:45:11.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2023-12-24T14:45:11.020+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:45:11.019+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2023-12-24T14:45:11.703+0000] {logging_mixin.py:188} INFO - [2023-12-24T14:45:11.700+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 15, in <module>
    from data_tools import SqlUtils
ModuleNotFoundError: No module named 'data_tools'
[2023-12-24T14:45:11.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2023-12-24T14:45:11.730+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/load_data.py took 0.726 seconds
